// <auto-generated />
namespace QUIZ_SYSTEM.Migrations.QUIZ
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ChangeCat_fk_catidToCat_IddInTbl_CategoryAndAddSD_IDInTBL_SETEXAM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangeCat_fk_catidToCat_IddInTbl_CategoryAndAddSD_IDInTBL_SETEXAM));
        
        string IMigrationMetadata.Id
        {
            get { return "202002220916144_ChangeCat_fk_catidToCat_IddInTbl_CategoryAndAddSD_IDInTBL_SETEXAM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
