// <auto-generated />
namespace QUIZ_SYSTEM.Migrations.QUIZ
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddCat_encryptedstringInTbl_Category : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCat_encryptedstringInTbl_Category));
        
        string IMigrationMetadata.Id
        {
            get { return "202002220848481_AddCat_encryptedstringInTbl_Category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
